var searchData=
[
  ['a',['A',['../namespaceokapi.html#af5040b3f1f33d27698871423e1453ab6a7fc56270e7a70fa81a5935b72eacbe29',1,'okapi']]],
  ['abs',['abs',['../classokapi_1_1RQuantity.html#a6c2615772058175dec0223d662c04b29',1,'okapi::RQuantity']]],
  ['abstractbutton',['AbstractButton',['../classokapi_1_1AbstractButton.html',1,'okapi']]],
  ['abstractbutton_2ecpp',['abstractButton.cpp',['../abstractButton_8cpp.html',1,'']]],
  ['abstractbutton_2ehpp',['abstractButton.hpp',['../abstractButton_8hpp.html',1,'']]],
  ['abstractmotor',['AbstractMotor',['../classokapi_1_1AbstractMotor.html',1,'okapi']]],
  ['abstractmotor_2ecpp',['abstractMotor.cpp',['../abstractMotor_8cpp.html',1,'']]],
  ['abstractmotor_2ehpp',['abstractMotor.hpp',['../abstractMotor_8hpp.html',1,'']]],
  ['abstractrate',['AbstractRate',['../classokapi_1_1AbstractRate.html',1,'okapi']]],
  ['abstractrate_2ecpp',['abstractRate.cpp',['../abstractRate_8cpp.html',1,'']]],
  ['abstractrate_2ehpp',['abstractRate.hpp',['../abstractRate_8hpp.html',1,'']]],
  ['abstracttimer',['AbstractTimer',['../classokapi_1_1AbstractTimer.html',1,'okapi::AbstractTimer'],['../classokapi_1_1AbstractTimer.html#aec03f7e11e25f300ec1fd44aaff3596f',1,'okapi::AbstractTimer::AbstractTimer()']]],
  ['abstracttimer_2ecpp',['abstractTimer.cpp',['../abstractTimer_8cpp.html',1,'']]],
  ['abstracttimer_2ehpp',['abstractTimer.hpp',['../abstractTimer_8hpp.html',1,'']]],
  ['accel',['accel',['../classokapi_1_1FlywheelSimulator.html#ae5fbfc008c5202fa9557087594d99e2b',1,'okapi::FlywheelSimulator::accel()'],['../classokapi_1_1VelMath.html#abe73288852f21916155e04266faea8b7',1,'okapi::VelMath::accel()']]],
  ['addfilter',['addFilter',['../classokapi_1_1ComposableFilter.html#a61d20215a1d89357c8720d04b23a31ed',1,'okapi::ComposableFilter']]],
  ['adibutton',['ADIButton',['../classokapi_1_1ADIButton.html',1,'okapi::ADIButton'],['../classokapi_1_1ADIButton.html#a84065174f1fd89bfb1aba7634c4c36d9',1,'okapi::ADIButton::ADIButton()']]],
  ['adibutton_2ecpp',['adiButton.cpp',['../adiButton_8cpp.html',1,'']]],
  ['adibutton_2ehpp',['adiButton.hpp',['../adiButton_8hpp.html',1,'']]],
  ['adiencoder',['ADIEncoder',['../classokapi_1_1ADIEncoder.html',1,'okapi::ADIEncoder'],['../classokapi_1_1ADIEncoder.html#ae60daf46ded27335225cc9b6522054c6',1,'okapi::ADIEncoder::ADIEncoder()']]],
  ['adiencoder_2ecpp',['adiEncoder.cpp',['../adiEncoder_8cpp.html',1,'']]],
  ['adiencoder_2ehpp',['adiEncoder.hpp',['../adiEncoder_8hpp.html',1,'']]],
  ['adigyro',['ADIGyro',['../classokapi_1_1ADIGyro.html',1,'okapi::ADIGyro'],['../classokapi_1_1ADIGyro.html#a04db661121327089b43d82f9aa21e168',1,'okapi::ADIGyro::ADIGyro()']]],
  ['adigyro_2ecpp',['adiGyro.cpp',['../adiGyro_8cpp.html',1,'']]],
  ['adigyro_2ehpp',['adiGyro.hpp',['../adiGyro_8hpp.html',1,'']]],
  ['adimotor',['ADIMotor',['../classokapi_1_1ADIMotor.html',1,'okapi::ADIMotor'],['../classokapi_1_1ADIMotor.html#ab7a6273a01d5a0dccb4da0696b0b2050',1,'okapi::ADIMotor::ADIMotor()']]],
  ['adimotor_2ecpp',['adiMotor.cpp',['../adiMotor_8cpp.html',1,'']]],
  ['adimotor_2ehpp',['adiMotor.hpp',['../adiMotor_8hpp.html',1,'']]],
  ['adiultrasonic',['ADIUltrasonic',['../classokapi_1_1ADIUltrasonic.html',1,'okapi::ADIUltrasonic'],['../classokapi_1_1ADIUltrasonic.html#aaa0b61d7e4d5657c4f1c6ce4925ee8e4',1,'okapi::ADIUltrasonic::ADIUltrasonic()']]],
  ['adiultrasonic_2ecpp',['adiUltrasonic.cpp',['../adiUltrasonic_8cpp.html',1,'']]],
  ['adiultrasonic_2ehpp',['adiUltrasonic.hpp',['../adiUltrasonic_8hpp.html',1,'']]],
  ['adiupdaterate',['adiUpdateRate',['../namespaceokapi.html#abf765c88ac34df87d378fb66ea5fd20c',1,'okapi']]],
  ['alpha',['alpha',['../classokapi_1_1DemaFilter.html#ab28fcb9de16e8df8c510e42b6be99323',1,'okapi::DemaFilter::alpha()'],['../classokapi_1_1EmaFilter.html#abaf5500df98574b5bf6f8d9a8a4331b5',1,'okapi::EmaFilter::alpha()']]],
  ['analogintov',['analogInToV',['../namespaceokapi.html#a2a1dadedbf4a0243e7671614e7664eb0',1,'okapi']]],
  ['analogtoprosenum',['analogToProsEnum',['../classokapi_1_1ControllerUtil.html#ae6459f27cc2567815ba9b6ce68c55239',1,'okapi::ControllerUtil']]],
  ['angle',['angle',['../classokapi_1_1ChassisControllerPID.html#a74792367688870f72f88c486c96b8368acbd60074aa1c74a74fec252c3bb87acd',1,'okapi::ChassisControllerPID::angle()'],['../classokapi_1_1FlywheelSimulator.html#ab52c0add6fc410b93ce91ff29bf3c85b',1,'okapi::FlywheelSimulator::angle()']]],
  ['anglepid',['anglePid',['../classokapi_1_1ChassisControllerPID.html#a22677f191a4014e51f4f133d56d3bc76',1,'okapi::ChassisControllerPID']]],
  ['api_2ehpp',['api.hpp',['../api_8hpp.html',1,'']]],
  ['arcade',['arcade',['../classokapi_1_1ChassisModel.html#a632d4c0b74747ab3b9c5a159a36bdd03',1,'okapi::ChassisModel::arcade()'],['../classokapi_1_1SkidSteerModel.html#a145f671aa2dd1c6991945929e4a3d97d',1,'okapi::SkidSteerModel::arcade()'],['../classokapi_1_1XDriveModel.html#a0489ac1303ad42f65e346adf1dfc986f',1,'okapi::XDriveModel::arcade()']]],
  ['asynccontroller',['AsyncController',['../classokapi_1_1AsyncController.html',1,'okapi']]],
  ['asynccontroller_2ehpp',['asyncController.hpp',['../asyncController_8hpp.html',1,'']]],
  ['asynccontroller_3c_20double_2c_20double_20_3e',['AsyncController&lt; double, double &gt;',['../classokapi_1_1AsyncController.html',1,'okapi']]],
  ['asynccontroller_3c_20std_3a_3astring_2c_20double_20_3e',['AsyncController&lt; std::string, double &gt;',['../classokapi_1_1AsyncController.html',1,'okapi']]],
  ['asynccontroller_3c_20std_3a_3astring_2c_20point_20_3e',['AsyncController&lt; std::string, Point &gt;',['../classokapi_1_1AsyncController.html',1,'okapi']]],
  ['asynclinearmotionprofilecontroller',['AsyncLinearMotionProfileController',['../classokapi_1_1AsyncLinearMotionProfileController.html',1,'okapi::AsyncLinearMotionProfileController'],['../classokapi_1_1AsyncLinearMotionProfileController.html#a6a5c233fef5c310eaac306467e6a402b',1,'okapi::AsyncLinearMotionProfileController::AsyncLinearMotionProfileController(const TimeUtil &amp;itimeUtil, const PathfinderLimits &amp;ilimits, const std::shared_ptr&lt; ControllerOutput&lt; double &gt;&gt; &amp;ioutput, const QLength &amp;idiameter, const AbstractMotor::GearsetRatioPair &amp;ipair, const std::shared_ptr&lt; Logger &gt; &amp;ilogger=Logger::getDefaultLogger())'],['../classokapi_1_1AsyncLinearMotionProfileController.html#a9d12f6da129f5c8f8c2c6ddad12274bf',1,'okapi::AsyncLinearMotionProfileController::AsyncLinearMotionProfileController(AsyncLinearMotionProfileController &amp;&amp;other)=delete']]],
  ['asynclinearmotionprofilecontroller_2ecpp',['asyncLinearMotionProfileController.cpp',['../asyncLinearMotionProfileController_8cpp.html',1,'']]],
  ['asynclinearmotionprofilecontroller_2ehpp',['asyncLinearMotionProfileController.hpp',['../asyncLinearMotionProfileController_8hpp.html',1,'']]],
  ['asyncmotionprofilecontroller',['AsyncMotionProfileController',['../classokapi_1_1AsyncMotionProfileController.html',1,'okapi::AsyncMotionProfileController'],['../classokapi_1_1AsyncMotionProfileController.html#a7552d4d18213b79ec0fc0e65a3294305',1,'okapi::AsyncMotionProfileController::AsyncMotionProfileController(const TimeUtil &amp;itimeUtil, const PathfinderLimits &amp;ilimits, const std::shared_ptr&lt; ChassisModel &gt; &amp;imodel, const ChassisScales &amp;iscales, const AbstractMotor::GearsetRatioPair &amp;ipair, const std::shared_ptr&lt; Logger &gt; &amp;ilogger=Logger::getDefaultLogger())'],['../classokapi_1_1AsyncMotionProfileController.html#ad5c9863c0a6be7c6b333703d8e778399',1,'okapi::AsyncMotionProfileController::AsyncMotionProfileController(AsyncMotionProfileController &amp;&amp;other)=delete']]],
  ['asyncmotionprofilecontroller_2ecpp',['asyncMotionProfileController.cpp',['../asyncMotionProfileController_8cpp.html',1,'']]],
  ['asyncmotionprofilecontroller_2ehpp',['asyncMotionProfileController.hpp',['../asyncMotionProfileController_8hpp.html',1,'']]],
  ['asyncmotionprofilecontrollerbuilder',['AsyncMotionProfileControllerBuilder',['../classokapi_1_1AsyncMotionProfileControllerBuilder.html',1,'okapi::AsyncMotionProfileControllerBuilder'],['../classokapi_1_1AsyncMotionProfileControllerBuilder.html#ab8f0219b48e74a8ceb72280f20f9b651',1,'okapi::AsyncMotionProfileControllerBuilder::AsyncMotionProfileControllerBuilder()']]],
  ['asyncmotionprofilecontrollerbuilder_2ecpp',['asyncMotionProfileControllerBuilder.cpp',['../asyncMotionProfileControllerBuilder_8cpp.html',1,'']]],
  ['asyncmotionprofilecontrollerbuilder_2ehpp',['asyncMotionProfileControllerBuilder.hpp',['../asyncMotionProfileControllerBuilder_8hpp.html',1,'']]],
  ['asyncposcontrollerbuilder',['AsyncPosControllerBuilder',['../classokapi_1_1AsyncPosControllerBuilder.html',1,'okapi::AsyncPosControllerBuilder'],['../classokapi_1_1AsyncPosControllerBuilder.html#ab5016bcf0679d7bae87d19d21cbff95f',1,'okapi::AsyncPosControllerBuilder::AsyncPosControllerBuilder()']]],
  ['asyncposcontrollerbuilder_2ecpp',['asyncPosControllerBuilder.cpp',['../asyncPosControllerBuilder_8cpp.html',1,'']]],
  ['asyncposcontrollerbuilder_2ehpp',['asyncPosControllerBuilder.hpp',['../asyncPosControllerBuilder_8hpp.html',1,'']]],
  ['asyncposintegratedcontroller',['AsyncPosIntegratedController',['../classokapi_1_1AsyncPosIntegratedController.html',1,'okapi::AsyncPosIntegratedController'],['../classokapi_1_1AsyncPosIntegratedController.html#a6017c7eeed0e2054ff325582c404de60',1,'okapi::AsyncPosIntegratedController::AsyncPosIntegratedController()']]],
  ['asyncposintegratedcontroller_2ecpp',['asyncPosIntegratedController.cpp',['../asyncPosIntegratedController_8cpp.html',1,'']]],
  ['asyncposintegratedcontroller_2ehpp',['asyncPosIntegratedController.hpp',['../asyncPosIntegratedController_8hpp.html',1,'']]],
  ['asyncpositioncontroller',['AsyncPositionController',['../classokapi_1_1AsyncPositionController.html',1,'okapi']]],
  ['asyncpositioncontroller_2ehpp',['asyncPositionController.hpp',['../asyncPositionController_8hpp.html',1,'']]],
  ['asyncpositioncontroller_3c_20double_2c_20double_20_3e',['AsyncPositionController&lt; double, double &gt;',['../classokapi_1_1AsyncPositionController.html',1,'okapi']]],
  ['asyncpositioncontroller_3c_20std_3a_3astring_2c_20double_20_3e',['AsyncPositionController&lt; std::string, double &gt;',['../classokapi_1_1AsyncPositionController.html',1,'okapi']]],
  ['asyncpositioncontroller_3c_20std_3a_3astring_2c_20point_20_3e',['AsyncPositionController&lt; std::string, Point &gt;',['../classokapi_1_1AsyncPositionController.html',1,'okapi']]],
  ['asyncpospidcontroller',['AsyncPosPIDController',['../classokapi_1_1AsyncPosPIDController.html',1,'okapi::AsyncPosPIDController'],['../classokapi_1_1AsyncPosPIDController.html#ad66e9890d43f60ed304a356b52baad80',1,'okapi::AsyncPosPIDController::AsyncPosPIDController(const std::shared_ptr&lt; ControllerInput&lt; double &gt;&gt; &amp;iinput, const std::shared_ptr&lt; ControllerOutput&lt; double &gt;&gt; &amp;ioutput, const TimeUtil &amp;itimeUtil, double ikP, double ikI, double ikD, double ikBias=0, double iratio=1, std::unique_ptr&lt; Filter &gt; iderivativeFilter=std::make_unique&lt; PassthroughFilter &gt;(), const std::shared_ptr&lt; Logger &gt; &amp;ilogger=Logger::getDefaultLogger())'],['../classokapi_1_1AsyncPosPIDController.html#a4038bde6275c8c69fc22edfbead726d2',1,'okapi::AsyncPosPIDController::AsyncPosPIDController(const std::shared_ptr&lt; OffsetableControllerInput &gt; &amp;iinput, const std::shared_ptr&lt; ControllerOutput&lt; double &gt;&gt; &amp;ioutput, const TimeUtil &amp;itimeUtil, double ikP, double ikI, double ikD, double ikBias=0, double iratio=1, std::unique_ptr&lt; Filter &gt; iderivativeFilter=std::make_unique&lt; PassthroughFilter &gt;(), const std::shared_ptr&lt; Logger &gt; &amp;ilogger=Logger::getDefaultLogger())']]],
  ['asyncpospidcontroller_2ecpp',['asyncPosPidController.cpp',['../asyncPosPidController_8cpp.html',1,'']]],
  ['asyncpospidcontroller_2ehpp',['asyncPosPidController.hpp',['../asyncPosPidController_8hpp.html',1,'']]],
  ['asyncvelcontrollerbuilder',['AsyncVelControllerBuilder',['../classokapi_1_1AsyncVelControllerBuilder.html',1,'okapi::AsyncVelControllerBuilder'],['../classokapi_1_1AsyncVelControllerBuilder.html#a2240959e5feeb59b630fe93e6e993996',1,'okapi::AsyncVelControllerBuilder::AsyncVelControllerBuilder()']]],
  ['asyncvelcontrollerbuilder_2ecpp',['asyncVelControllerBuilder.cpp',['../asyncVelControllerBuilder_8cpp.html',1,'']]],
  ['asyncvelcontrollerbuilder_2ehpp',['asyncVelControllerBuilder.hpp',['../asyncVelControllerBuilder_8hpp.html',1,'']]],
  ['asyncvelintegratedcontroller',['AsyncVelIntegratedController',['../classokapi_1_1AsyncVelIntegratedController.html',1,'okapi::AsyncVelIntegratedController'],['../classokapi_1_1AsyncVelIntegratedController.html#a8b272566332633b02aca9c8ea585e8f9',1,'okapi::AsyncVelIntegratedController::AsyncVelIntegratedController()']]],
  ['asyncvelintegratedcontroller_2ecpp',['asyncVelIntegratedController.cpp',['../asyncVelIntegratedController_8cpp.html',1,'']]],
  ['asyncvelintegratedcontroller_2ehpp',['asyncVelIntegratedController.hpp',['../asyncVelIntegratedController_8hpp.html',1,'']]],
  ['asyncvelocitycontroller',['AsyncVelocityController',['../classokapi_1_1AsyncVelocityController.html',1,'okapi']]],
  ['asyncvelocitycontroller_2ehpp',['asyncVelocityController.hpp',['../asyncVelocityController_8hpp.html',1,'']]],
  ['asyncvelocitycontroller_3c_20double_2c_20double_20_3e',['AsyncVelocityController&lt; double, double &gt;',['../classokapi_1_1AsyncVelocityController.html',1,'okapi']]],
  ['asyncvelpidcontroller',['AsyncVelPIDController',['../classokapi_1_1AsyncVelPIDController.html',1,'okapi::AsyncVelPIDController'],['../classokapi_1_1AsyncVelPIDController.html#af1f3d7f4b31514ca97500265f5e3295e',1,'okapi::AsyncVelPIDController::AsyncVelPIDController()']]],
  ['asyncvelpidcontroller_2ecpp',['asyncVelPidController.cpp',['../asyncVelPidController_8cpp.html',1,'']]],
  ['asyncvelpidcontroller_2ehpp',['asyncVelPidController.hpp',['../asyncVelPidController_8hpp.html',1,'']]],
  ['asyncwrapper',['AsyncWrapper',['../classokapi_1_1AsyncWrapper.html',1,'okapi::AsyncWrapper&lt; Input, Output &gt;'],['../classokapi_1_1AsyncWrapper.html#adbbf06146d19a3fd5747f6ddd8bc084e',1,'okapi::AsyncWrapper::AsyncWrapper(const std::shared_ptr&lt; ControllerInput&lt; Input &gt;&gt; &amp;iinput, const std::shared_ptr&lt; ControllerOutput&lt; Output &gt;&gt; &amp;ioutput, std::unique_ptr&lt; IterativeController&lt; Input, Output &gt;&gt; icontroller, const Supplier&lt; std::unique_ptr&lt; AbstractRate &gt;&gt; &amp;irateSupplier, const double iratio=1, const std::shared_ptr&lt; Logger &gt; &amp;ilogger=Logger::getDefaultLogger())'],['../classokapi_1_1AsyncWrapper.html#a6824804fd4c85627d6af2a563ea9fcf0',1,'okapi::AsyncWrapper::AsyncWrapper(AsyncWrapper&lt; Input, Output &gt; &amp;&amp;other)=delete']]],
  ['asyncwrapper_2ehpp',['asyncWrapper.hpp',['../asyncWrapper_8hpp.html',1,'']]],
  ['asyncwrapper_3c_20double_2c_20double_20_3e',['AsyncWrapper&lt; double, double &gt;',['../classokapi_1_1AsyncWrapper.html',1,'okapi']]],
  ['attargetderivative',['atTargetDerivative',['../classokapi_1_1SettledUtil.html#a972febaf6427ee6ea67d007da2ffbf0a',1,'okapi::SettledUtil']]],
  ['attargeterror',['atTargetError',['../classokapi_1_1SettledUtil.html#ae90caf556f0702edea6c86bd6e9a888f',1,'okapi::SettledUtil']]],
  ['attargettime',['atTargetTime',['../classokapi_1_1SettledUtil.html#a723f415c2860413c22b8467db4a55586',1,'okapi::SettledUtil']]],
  ['attargettimer',['atTargetTimer',['../classokapi_1_1SettledUtil.html#aebaa16b34b04ee6c7938418f83d47e56',1,'okapi::SettledUtil']]],
  ['autotune',['autotune',['../classokapi_1_1PIDTuner.html#af67c498c38c49118876d592bb54a251d',1,'okapi::PIDTuner']]],
  ['averagefilter',['AverageFilter',['../classokapi_1_1AverageFilter.html',1,'okapi::AverageFilter&lt; n &gt;'],['../classokapi_1_1AverageFilter.html#a21483cccbe9d9aa49200c3b4b6d8a878',1,'okapi::AverageFilter::AverageFilter()']]],
  ['averagefilter_2ehpp',['averageFilter.hpp',['../averageFilter_8hpp.html',1,'']]]
];
